export const supabaseUrl = "https://bulppyzkvtcojszmmdbj.supabase.co";
export const supabaseAnonKey =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ1bHBweXprdnRjb2pzem1tZGJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mjg3NDUxODAsImV4cCI6MjA0NDMyMTE4MH0.cugjDEEgWoJRzq_kA5ejdxLc89c5SckvU7_yMen1_U4";
